ARG BASE_IMAGE=node:22-bullseye-slim
FROM ${BASE_IMAGE}

WORKDIR /app

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build -w @blinds/storefront

ENV NODE_ENV=production

EXPOSE 8080

CMD ["sh", "-c", "npm run start -w @blinds/storefront -- --hostname 0.0.0.0 -p ${PORT:-8080}"]
